import { defineContentConfig, defineCollection, z } from '@nuxt/content'

const eventSchema = z.object({
  date: z.string().optional().default(''),
  sortDate: z.string().optional(),
  candidateDates: z.array(z.string()).optional(),
  dateStatus: z.enum(['confirmed', 'disputed']).optional(),
  endDate: z.string().optional(),
  dates: z.array(z.string()).optional(),
  displayDate: z.string().optional(),
  displayAsRange: z.boolean().optional(),
  name: z.string(),
  type: z.enum([
    'school_start', 'school_end', 'school_resume', 'school_reopen',
    'holiday', 'closure', 'no_school', 'student_holiday',
    'break', 'break_start', 'break_end',
    'early_release', 'early_dismissal', 'early_close',
    'operational_closure',
    'academic', 'observance', 'teacher_workday', 'staff_development',
    'contingency', 'conference',
    'makeup_day', 'quarter_start', 'quarter_end', 'semester_end', 'graduation',
  ]),
  description: z.string().optional(),
  sectionLabelBefore: z.string().optional(),
  schemaDescription: z.string().optional(),
  hideSchemaDescription: z.boolean().optional(),
  calendarExportDescription: z.string().optional(),
  exportDatesIndividually: z.boolean().optional(),
  showDuringBreak: z.boolean().optional(),
  badgeLabel: z.string().optional(),
  labelType: z.string().optional(),
  isDerivedPlanningDate: z.boolean().optional(),
  preserveOfficialName: z.boolean().optional(),
  hideFromAllDates: z.boolean().optional(),
  hideFromCalendarExport: z.boolean().optional(),
  excludeFromDateSchema: z.boolean().optional(),
  calendarExportTracks: z.array(z.string()).optional(),
}).refine(event => Boolean(event.date || event.sortDate), {
  message: 'Calendar events require either date or sortDate',
})

const relatedDistrictSchema = z.object({
  name: z.string(),
  slug: z.string(),
  state: z.string(),
  linkLabel: z.string().optional(),
  comparisonNote: z.string().optional(),
})

const districtAboutCardSchema = z.object({
  title: z.string(),
  content: z.string(),
})

const districtSourceSchema = z.object({
  label: z.string(),
  url: z.string().optional(),
})

const districtFaqSchema = z.object({ q: z.string(), a: z.string() })
const customSectionGroupSchema = z.object({
  label: z.string(),
  items: z.array(z.string()),
})
const customSectionLinkSchema = z.object({
  label: z.string(),
  to: z.string(),
  description: z.string().optional(),
})
const customSectionTableSchema = z.object({
  caption: z.string().optional(),
  columns: z.array(z.string()),
  rows: z.array(z.array(z.string())),
  footnote: z.string().optional(),
})
const customSectionSchema = z.object({
  id: z.string(),
  label: z.string(),
  content: z.string(),
  position: z.string().optional(), // 'afterAbout' | 'afterFaq' | 'afterPlanningTips' | 'beforeSources'
  hideGroupLabels: z.boolean().optional(),
  groups: z.array(customSectionGroupSchema).optional(),
  links: z.array(customSectionLinkSchema).optional(),
  table: customSectionTableSchema.optional(),
})
const gradingPeriodSchema = z.object({
  label: z.string(),
  start: z.string().optional(),
  end: z.string(),
  nextStudentDate: z.string().optional(),
  studentDays: z.number().optional(),
  reportsIssued: z.string().optional(),
  secondaryReportDate: z.string().optional(),
  elementaryReportDate: z.string().optional(),
})

const livingHereHighlightSchema = z.object({ label: z.string(), detail: z.string() })
const livingHereSchema = z.object({
  intro: z.string().optional(),
  highlights: z.array(livingHereHighlightSchema),
})

const stateQuickFactSchema = z.object({ label: z.string(), value: z.string() })
const stateFaqSchema = z.object({ q: z.string(), a: z.string() })
const relatedStateSchema = z.object({ name: z.string(), slug: z.string() })
const stateCalendarRuleSchema = z.object({
  label: z.string(),
  description: z.string().optional(),
})
const statePopularDistrictSchema = z.object({
  label: z.string(),
  slug: z.string().optional(),
  area: z.string().optional(),
  note: z.string().optional(),
})
const stateDistrictClusterSchema = z.object({
  label: z.string(),
  description: z.string().optional(),
  districts: z.array(z.object({
    label: z.string(),
    slug: z.string(),
    note: z.string().optional(),
  })),
})

export default defineContentConfig({
  collections: {
    // Stable institution identity — one file per institution
    districts: defineCollection({
      type: 'data',
      source: 'districts/*.json',
      schema: z.object({
        institutionId: z.string(),
        name: z.string(),
        shortName: z.string().optional(),
        slug: z.string(),
        state: z.string(),
        stateCode: z.string(),
        city: z.string().optional(),
        country: z.string().optional(),
        type: z.enum(['public_district', 'charter', 'private', 'university', 'preschool']).optional(),
        grades: z.array(z.string()).optional(),
        officialWebsite: z.string(),
        calendarPage: z.string().optional(),
        logo: z.string().optional(),
        timezone: z.string().optional(),
        currentSchoolYear: z.string(),
        allDatesMode: z.enum(['all', 'keyDates']).optional(),
        studentCount: z.number().optional(),
        studentCountAsOf: z.string().optional(),
        studentCountSourceLabel: z.string().optional(),
        studentCountSourceUrl: z.string().optional(),
        profileStudentCountApproximate: z.boolean().optional(),
        schoolCount: z.number().optional(),
        profileSchoolCountExact: z.boolean().optional(),
        founded: z.number().optional(),
        calendarType: z.string().optional(),
        hideProfileCalendarType: z.boolean().optional(),
        districtFact: z.string().optional(),
        profileDisclaimer: z.string().optional(),
        about: z.array(districtAboutCardSchema).optional(),
        calendarNotes: z.string().optional(),
        county: z.string().optional(),
        region: z.string().optional(),
        metro: z.string().optional(),
        seoTitle: z.string().optional(),
        seoDescription: z.string().optional(),
        districtFaqs: z.array(districtFaqSchema).optional(),
        planningTips: z.object({
          title: z.string().optional(),
          content: z.array(z.string()),
        }).optional(),
        livingHere: livingHereSchema.optional(),
        relatedDistricts: z.array(relatedDistrictSchema).optional(),
        relatedDistrictsTitle: z.string().optional(),
        relatedDistrictsDescription: z.string().optional(),
        compareIntro: z.string().optional(),  // sentence(s) shown above the calendar comparison table
        sources: z.array(districtSourceSchema).optional(),
        // Section customization
        hiddenSections: z.array(z.string()).optional(),
        hideRelatedDistrictDescriptions: z.boolean().optional(),
        relatedDistrictsTitle: z.string().optional(),
        relatedDistrictsDescription: z.string().optional(),
        includeComparisonSchema: z.boolean().optional(),
        faqLimit: z.number().optional(),
        faqSchemaLimit: z.number().optional(),
        faqSchemaExclude: z.array(z.string()).optional(),
        customSections: z.array(customSectionSchema).optional(),
      }),
    }),

    // State-level topic pages — one file per state
    states: defineCollection({
      type: 'data',
      source: 'states/*.json',
      schema: z.object({
        stateSlug: z.string(),
        stateName: z.string(),
        stateCode: z.string(),
        lastVerifiedAt: z.string().optional(),
        pageHeading: z.string().optional(),
        seoTitle: z.string().optional(),
        seoDescription: z.string().optional(),
        heroDescription: z.string().optional(),
        browseLabel: z.string().optional(),
        officialSourceLabel: z.string().optional(),
        quickAnswerNavLabel: z.string().optional(),
        quickAnswerTitle: z.string().optional(),
        quickAnswer: z.string().optional(),
        quickAnswerItems: z.array(stateQuickFactSchema).optional(),
        hideDistrictCalendarStats: z.boolean().optional(),
        hideNationalContext: z.boolean().optional(),
        includeFaqSchema: z.boolean().optional(),
        footerNote: z.string().optional(),
        about: z.string(),
        calendarRulesDescription: z.string().optional(),
        calendarRules: z.array(stateCalendarRuleSchema).optional(),
        quickFacts: z.array(stateQuickFactSchema),
        stateSections: z.array(customSectionSchema).optional(),
        collectionNavLabel: z.string().optional(),
        collectionHeading: z.string().optional(),
        collectionDescription: z.string().optional(),
        planningTips: z.array(z.string()),
        commonHolidays: z.array(z.string()),
        commonHolidaysDescription: z.string().optional(),
        popularDistrictsHeading: z.string().optional(),
        popularDistrictsDescription: z.string().optional(),
        popularDistricts: z.array(statePopularDistrictSchema).optional(),
        clustersHeading: z.string().optional(),
        clustersDescription: z.string().optional(),
        districtClusters: z.array(stateDistrictClusterSchema).optional(),
        verificationMethodology: z.array(z.string()).optional(),
        faqs: z.array(stateFaqSchema),
        relatedStates: z.array(relatedStateSchema),
      }),
    }),

    // Per-year calendar data — one file per institution per year
    calendars: defineCollection({
      type: 'data',
      source: 'calendars/*/*.json',
      schema: z.object({
        institutionId: z.string(),
        schoolYear: z.string(),
        firstDay: z.string(),
        firstDayScope: z.string().optional(),
        firstFullK12Day: z.string().optional(),
        earlyChildhoodFirstDay: z.string().optional(),
        lastDay: z.string(),
        lastDayScope: z.string().optional(),
        seniorLastDay: z.string().optional(),
        earlyChildhoodLastDay: z.string().optional(),
        k11LastDay: z.string().optional(),
        temporalCoverageStart: z.string().optional(),
        temporalCoverageEnd: z.string().optional(),
        totalSchoolDays: z.number().optional(),
        reportingPeriodDaysTotal: z.number().optional(),
        reportingPeriodDaysScope: z.string().optional(),
        teacherWorkDays: z.number().optional(),
        semesters: z.number().optional(),
        sourceUrl: z.string().optional(),      // alias: sourcePageUrl (stable hub, district-level)
        sourceDocumentPage: z.string().optional(), // stable official record for the current source document
        sourcePdfUrl: z.string().optional(),   // direct official PDF for this school year (changes annually)
        previousSourcePdfUrl: z.string().optional(),
        lastCheckedPdfUrl: z.string().optional(), // direct PDF resolved from the official document record at last check
        sourceCheckedAt: z.string().optional(),
        sourceUpdatedAt: z.string().optional(),
        sourceChecksumSha256: z.string().optional(),
        previousSourceChecksumSha256: z.string().optional(),
        reviewedSourcePdfUrl: z.string().optional(),
        reviewedSourceUpdatedAt: z.string().optional(),
        reviewedSourceChecksumSha256: z.string().optional(),
        sourceStatus: z.enum(['current', 'changed', 'unavailable']).optional(),
        manualReviewRequired: z.boolean().optional(),
        sourceConflict: z.boolean().optional(),
        sourceConflictNote: z.string().optional(),
        sourceResourceMonitor: z.object({
          type: z.enum(['resource-uuid', 'document-pdf', 'web-page']).optional(),
          checkUrl: z.string(),
          sectionText: z.string().optional(),
          linkText: z.string(),
          expectedDocumentUrl: z.string().optional(),
          expectedText: z.array(z.string()).optional(),
          contentAssertions: z.array(z.object({
            startText: z.string(),
            endText: z.string().optional(),
            expectedText: z.array(z.string()).optional(),
            forbiddenText: z.array(z.string()).optional(),
          })).optional(),
          expectedResourceUuid: z.string().optional(),
          expectedPdfUrl: z.string().optional(),
          expectedChecksumSha256: z.string().optional(),
        }).optional(),
        additionalSourceResourceMonitors: z.array(z.object({
          type: z.enum(['resource-uuid', 'document-pdf', 'web-page']).optional(),
          checkUrl: z.string(),
          sectionText: z.string().optional(),
          linkText: z.string(),
          expectedDocumentUrl: z.string().optional(),
          expectedText: z.array(z.string()).optional(),
          contentAssertions: z.array(z.object({
            startText: z.string(),
            endText: z.string().optional(),
            expectedText: z.array(z.string()).optional(),
            forbiddenText: z.array(z.string()).optional(),
          })).optional(),
          expectedResourceUuid: z.string().optional(),
          expectedPdfUrl: z.string().optional(),
          expectedChecksumSha256: z.string().optional(),
        })).optional(),
        printablePdfUrl: z.string().optional(), // MySchoolDates-generated printable PDF for this school year
        lastVerifiedAt: z.string().optional(), // ISO date: when data was last verified against official source
        dateCreated: z.string().optional(),
        datePublished: z.string().optional(),
        dateModified: z.string().optional(),
        contentStatus: z.enum(['draft', 'in_review', 'production_ready', 'needs_update']).optional(),
        contentReviewTriggers: z.array(z.enum([
          'official_calendar_revision',
          'official_source_conflict',
          'official_schedule_change',
          'start_dismissal_schedule_change',
          'makeup_day_activation',
          'confirmed_data_error',
        ])).optional(),
        sourceVersion: z.string().optional(),
        sourceVersionLabel: z.string().optional(),
        sourceVersionDisplay: z.string().optional(),
        sourceCalendarDateModified: z.string().optional(),
        hideSourceVersionDisplay: z.boolean().optional(),
        hideSemesterCount: z.boolean().optional(),
        displaySchoolYear: z.string().optional(),
        sourceCalendarName: z.string().optional(),
        schemaCalendarName: z.string().optional(),
        schemaDatasetName: z.string().optional(),
        schemaDatasetDescription: z.string().optional(),
        schemaSpatialCoverage: z.union([
          z.string(),
          z.object({
            '@type': z.string().optional(),
            name: z.string(),
          }),
          z.array(z.union([
            z.string(),
            z.object({
              '@type': z.string().optional(),
              name: z.string(),
            }),
          ])),
        ]).optional(),
        schemaCalendarDownloadName: z.string().optional(),
        schemaCalendarDownloadDescription: z.string().optional(),
        schemaAdditionalSourceCalendars: z.array(z.object({
          id: z.string().optional(),
          type: z.string().optional(),
          name: z.string(),
          url: z.string(),
          version: z.string().optional(),
          dateCreated: z.string().optional(),
          dateModified: z.string().optional(),
          datePublished: z.string().optional(),
          sameAs: z.string().optional(),
          publisherName: z.string().optional(),
          publisherUrl: z.string().optional(),
        })).optional(),
        schemaDatasetSourceCalendarIds: z.array(z.string()).optional(),
        schemaWebPageIsBasedOnSourceIds: z.array(z.string()).optional(),
        webPageMainEntity: z.enum(['none', 'keyDates', 'dataset']).optional(),
        includeArticleSchema: z.boolean().optional(),
        hideFaqSchema: z.boolean().optional(),
        hideCalendarTrackCaution: z.boolean().optional(),
        hideAlternateCalendarsNotice: z.boolean().optional(),
        heroFactChips: z.array(z.string()).optional(),
        keyDatesHeading: z.string().optional(),
        keyDatesSummaryTitle: z.string().optional(),
        keyDatesSummarySubtitle: z.string().optional(),
        keyDatesSummaryId: z.string().optional(),
        keyDateSummaryItems: z.array(z.record(z.string(), z.unknown())).optional(),
        allDatesTitle: z.string().optional(),
        allDatesIncludedDatesInKeyDates: z.array(z.string()).optional(),
        allDatesCoverageNote: z.string().optional(),
        allDatesCoverageNotePosition: z.enum(['top', 'bottom', 'both']).optional(),
        allDatesFooterMode: z.enum(['default', 'source_sentence']).optional(),
        allDatesMonthNotes: z.record(z.string(), z.string()).optional(),
        allDatesSourceUrl: z.string().optional(),
        allDatesSourceLabel: z.string().optional(),
        allDatesSourceSuffix: z.string().optional(),
        allDatesSourceLinks: z.array(z.object({
          label: z.string(),
          url: z.string(),
        })).optional(),
        allDatesDerivedDateNote: z.string().optional(),
        allDatesDerivedDateNotePosition: z.enum(['event', 'footer']).optional(),
        dateLegendItems: z.array(z.object({
          label: z.string(),
          dot: z.string(),
        })).optional(),
        dateLegendLabelOverrides: z.record(z.string(), z.string()).optional(),
        breaksTitle: z.string().optional(),
        hideBreakDurationBadges: z.boolean().optional(),
        breaksBeforeAllDates: z.boolean().optional(),
        breakNotes: z.record(z.string(), z.string()).optional(),
        unifiedDownloadTitle: z.string().optional(),
        unifiedDownloadDescription: z.string().optional(),
        compactDownloadModule: z.boolean().optional(),
        pdfHeading: z.string().optional(),
        pdfHeadingTag: z.enum(['h2', 'h3', 'h4']).optional(),
        pdfDescription: z.string().optional(),
        pdfVersionLabel: z.string().optional(),
        pdfButtonLabel: z.string().optional(),
        hidePdfVersionLabel: z.boolean().optional(),
        groupAlternateCalendarsWithDownloads: z.boolean().optional(),
        shareCalendarHeading: z.string().optional(),
        hideShareCalendarHeading: z.boolean().optional(),
        hideSocialShareButtons: z.boolean().optional(),
        icsHeading: z.string().optional(),
        icsDescription: z.string().optional(),
        icsButtonLabel: z.string().optional(),
        icsButtonSupportText: z.string().optional(),
        icsSourceNote: z.string().optional(),
        hideIcsButtonSupportText: z.boolean().optional(),
        hideIcsImportDisclaimer: z.boolean().optional(),
        officialSubscriptionTitle: z.string().optional(),
        officialSubscriptionDescription: z.string().optional(),
        officialSubscriptionButtonLabel: z.string().optional(),
        officialSubscriptionUrl: z.string().optional(),
        combinedIcsButtonLabel: z.string().optional(),
        hiddenCustomSectionIds: z.array(z.string()).optional(),
        preserveJumpNavigationOrder: z.boolean().optional(),
        jumpNavigation: z.array(z.object({
          label: z.string(),
          href: z.string().optional(),
          id: z.string().optional(),
        })).optional(),
        faqOrderLimit: z.number().optional(),
        excludeDistrictFaqs: z.boolean().optional(),
        faqDisplayQuestions: z.array(z.string()).optional(),
        sourceReviewSummary: z.string().optional(),
        sourcesTitle: z.string().optional(),
        sourceReviewDetails: z.array(z.string()).optional(),
        sourceReviewDetailsTitle: z.string().optional(),
        sourceMaintainerLabel: z.string().optional(),
        sourceMaintainerText: z.string().optional(),
        sourceNextReviewText: z.string().optional(),
        hideSourceNextReview: z.boolean().optional(),
        hideSourceReviewAuthor: z.boolean().optional(),
        sources: z.array(districtSourceSchema).optional(),
        quickFacts: z.array(z.object({
          label: z.string(),
          value: z.string(),
        })).optional(),
        hideQuickFactsReviewDate: z.boolean().optional(),
        yearNumbersMode: z.enum(['compact']).optional(),
        instructionalDaysLabel: z.string().optional(),
        instructionalDaysDescription: z.string().optional(),
        pageHeading: z.string().optional(),
        faqLimit: z.number().optional(),
        faqSchemaLimit: z.number().optional(),
        faqSchemaExclude: z.array(z.string()).optional(),
        hiddenSections: z.array(z.string()).optional(),
        comparisonBeforeFaq: z.boolean().optional(),
        comparisonAfterSources: z.boolean().optional(),
        comparisonTitle: z.string().optional(),
        comparisonSummary: z.string().optional(),
        comparisonDistrictSlugs: z.array(z.string()).optional(),
        relatedDistrictsSameYearOnly: z.boolean().optional(),
        comparisonRowsInclude: z.array(z.string()).optional(),
        comparisonRanges: z.record(z.string(), z.object({
          start: z.string(),
          end: z.string(),
        })).optional(),
        comparisonRowLabels: z.record(z.string(), z.string()).optional(),
        comparisonSourceNote: z.string().optional(),
        hideComparisonNotes: z.boolean().optional(),
        hideComparisonReviewedDate: z.boolean().optional(),
        hideRelatedDistrictDescriptions: z.boolean().optional(),
        yearSwitcherPosition: z.enum(['default', 'afterKeyDates', 'afterSources']).optional(),
        hideInstructionalDaysSummary: z.boolean().optional(),
        hideHeroVerificationIcs: z.boolean().optional(),
        hidePdfDownloadSection: z.boolean().optional(),
        hideCoveredBreakDatesNote: z.boolean().optional(),
        keyDateCardsVariant: z.enum(['compact']).optional(),
        keyDateCardsFirstLabel: z.string().optional(),
        keyDateCardsSecondLabel: z.string().optional(),
        keyDateCardsSecondValue: z.string().optional(),
        keyDateCardsSecondDate: z.string().optional(),
        keyDateCardsThirdLabel: z.string().optional(),
        keyDateCardsThirdValue: z.string().optional(),
        keyDateCardsThirdDate: z.string().optional(),
        keyDateCardsThirdNote: z.string().optional(),
        includeComparisonSchema: z.boolean().optional(),
        hideDatasetSchema: z.boolean().optional(),
        itemListMode: z.enum(['keyDates', 'allImportantDates']).optional(),
        gradingPeriodsPosition: z.enum(['beforeCalendarExport']).optional(),
        gradingPeriodsTitle: z.string().optional(),
        gradingPeriodsDescription: z.string().optional(),
        gradingPeriodsDaysLabel: z.string().optional(),
        gradingPeriodsReportsLabel: z.string().optional(),
        gradingPeriodsFooterNote: z.string().optional(),
        gradingPeriods: z.array(gradingPeriodSchema).optional(),
        breakSummaryOverrides: z.record(z.string(), z.object({
          name: z.string().optional(),
          start: z.string().optional(),
          end: z.string().optional(),
          note: z.string().optional(),
          durationLabel: z.string().optional(),
        })).optional(),
        heroSummary: z.string().optional(),
        heroSourceLine: z.string().optional(),
        heroDownloadLabel: z.string().optional(),
        verificationBadgeText: z.string().optional(),
        hideHeroReviewedField: z.boolean().optional(),
        hideHeroReviewedByField: z.boolean().optional(),
        hideHeroUpdatedField: z.boolean().optional(),
        hideHeroVerificationProcess: z.boolean().optional(),
        heroVerificationHeading: z.string().optional(),
        heroVerificationSourceText: z.string().optional(),
        heroVerificationComparisonText: z.string().optional(),
        heroVerificationIcsText: z.string().optional(),
        calendarNotes: z.string().optional(),  // year-specific narrative (moved from districts/)
        calendarType: z.enum(['traditional', 'balanced', 'modified-start', 'year-round', 'magnet', 'international', 'early-college', 'alternative']).optional(),
        calendarTrackId: z.string().optional(),
        otherCalendarsPosition: z.enum(['beforeKeyDates', 'afterKeyDates', 'afterFaq', 'beforeCalendarExport']).optional(),
        alternateCalendarsTitle: z.string().optional(),
        alternateCalendarsButtonLabel: z.string().optional(),
        alternateCalendarsCollapsible: z.boolean().optional(),
        alternateCalendarsSummaryLabel: z.string().optional(),
        calendarTrackDownloads: z.array(z.object({
          id: z.string(),
          label: z.string(),
          description: z.string().optional(),
          ariaLabel: z.string().optional(),
        })).optional(),
        alternateCalendars: z.array(z.object({
          type: z.string(),
          label: z.string(),
          description: z.string().optional(),
          group: z.string().optional(),
          pdfUrl: z.string().optional(),
          firstDay: z.string().optional(),
          buttonLabel: z.string().optional(),
          ariaLabel: z.string().optional(),
        })).optional(),
        alternateCalendarsDescription: z.string().optional(),
        relatedDistrictsTitle: z.string().optional(),
        relatedDistrictsDescription: z.string().optional(),
        seoTitle: z.string().optional(),
        seoDescription: z.string().optional(),
        calendarFaqs: z.array(districtFaqSchema).optional(),
        customSections: z.array(customSectionSchema).optional(),
        yearNumbers: z.array(z.object({
          label: z.string(),
          value: z.string(),
          detail: z.string(),
        })).optional(),
        yearComparisonTitle: z.string().optional(),
        yearComparisonSubtitle: z.string().optional(),
        yearComparisonStyle: z.enum(['default', 'movement', 'movement-simple']).optional(),
        hideThanksgivingYearComparison: z.boolean().optional(),
        whatsNew: z.object({
          title: z.string().optional(),
          subtitle: z.string().optional(),
          content: z.array(z.string()),
        }).optional(),
        events: z.array(eventSchema),
      }),
    }),
  },
})
