<script setup lang="ts">
const props = defineProps<{
  districtName: string
  year: string
  sourceUrl: string
  district: any
  cal: any
}>()

const pdfUrl = computed(() => String(props.cal?.sourcePdfUrl ?? props.cal?.printablePdfUrl ?? ''))
const hasOfficialPdf = computed(() => Boolean(props.cal?.sourcePdfUrl))
const hasGeneratedPrintablePdf = computed(() => !hasOfficialPdf.value && Boolean(props.cal?.printablePdfUrl))
const isDrivePdf = computed(() => pdfUrl.value.includes('drive.google.com'))
const isArchivedPdfCopy = computed(() => pdfUrl.value.includes('assets.myschooldates.com'))
const compactDownloadModule = computed(() => Boolean(props.cal?.compactDownloadModule ?? props.cal?.meta?.compactDownloadModule))
const hideCompatibleCalendars = computed(() => Boolean(props.cal?.hideCompatibleCalendars ?? props.cal?.meta?.hideCompatibleCalendars))
const hidePdfVersionLabel = computed(() => Boolean(props.cal?.hidePdfVersionLabel ?? props.cal?.meta?.hidePdfVersionLabel))
const hideShareCalendarHeading = computed(() => Boolean(props.cal?.hideShareCalendarHeading ?? props.cal?.meta?.hideShareCalendarHeading))
const hideIcsButtonSupportText = computed(() => Boolean(props.cal?.hideIcsButtonSupportText ?? props.cal?.meta?.hideIcsButtonSupportText))
const hideCalendarUpdatesButton = computed(() => Boolean(props.cal?.hideCalendarUpdatesButton ?? props.cal?.meta?.hideCalendarUpdatesButton))
const unifiedDownloadTitle = computed(() => props.cal?.unifiedDownloadTitle ?? props.cal?.meta?.unifiedDownloadTitle ?? '')
const unifiedDownloadDescription = computed(() => props.cal?.unifiedDownloadDescription ?? props.cal?.meta?.unifiedDownloadDescription ?? '')
const officialSubscriptionTitle = computed(() => props.cal?.officialSubscriptionTitle ?? props.cal?.meta?.officialSubscriptionTitle ?? '')
const officialSubscriptionDescription = computed(() => props.cal?.officialSubscriptionDescription ?? props.cal?.meta?.officialSubscriptionDescription ?? '')
const officialSubscriptionButtonLabel = computed(() => props.cal?.officialSubscriptionButtonLabel ?? props.cal?.meta?.officialSubscriptionButtonLabel ?? 'Subscribe to Official Calendar')
const officialSubscriptionUrl = computed(() => props.cal?.officialSubscriptionUrl ?? props.cal?.meta?.officialSubscriptionUrl ?? '')
const displayYear = computed(() => props.cal?.displaySchoolYear ?? props.cal?.meta?.displaySchoolYear ?? props.year)
const pdfHeading = computed(() => {
  const customHeading = props.cal?.pdfHeading ?? props.cal?.meta?.pdfHeading
  if (customHeading) return customHeading
  if (isArchivedPdfCopy.value) return `${props.districtName} Calendar ${displayYear.value}: Official Calendar PDF — Archived Copy`
  if (hasGeneratedPrintablePdf.value) return `${props.districtName} Calendar ${displayYear.value}: Printable PDF`
  if (isDrivePdf.value) return `${props.districtName} Calendar ${displayYear.value}: Printable PDF`
  return `${props.districtName} Calendar ${displayYear.value}: Printable PDF`
})
const pdfDescription = computed(() => {
  const customDescription = props.cal?.pdfDescription ?? props.cal?.meta?.pdfDescription
  if (customDescription) return customDescription
  if (isArchivedPdfCopy.value) {
    return `This is an archived copy of the official ${props.year} calendar published by ${props.districtName}. MySchoolDates stores the file for reliable long-term access because original district file URLs may expire. Check the official district source for revisions or newer versions.`
  }
  if (hasGeneratedPrintablePdf.value) {
    return `Download a printable PDF generated by MySchoolDates from the reviewed ${props.year} ${props.districtName} calendar records. The official district calendar remains the source of record for revisions and last-minute changes.`
  }
  if (isDrivePdf.value) {
    return `Open or print the calendar PDF linked from the ${props.districtName} calendar page. Check the district calendar page for revisions before making travel or child care plans.`
  }
  return `Open or print the official calendar PDF published by ${props.districtName}. Check the district calendar page for revisions before making travel or child care plans.`
})
const pdfVersionLabel = computed(() =>
  props.cal?.pdfVersionLabel ?? props.cal?.meta?.pdfVersionLabel ?? props.cal?.sourceVersion ?? ''
)
const pdfButtonLabel = computed(() => {
  const customLabel = props.cal?.pdfButtonLabel ?? props.cal?.meta?.pdfButtonLabel
  if (customLabel) return customLabel
  if (isArchivedPdfCopy.value) return 'View Archived Copy of Official PDF'
  if (hasGeneratedPrintablePdf.value) return 'Download Printable PDF Calendar'
  if (isDrivePdf.value) return 'Download PDF'
  return 'View Official PDF'
})
const pdfSupplementalTitle = computed(() => props.cal?.pdfSupplementalTitle ?? props.cal?.meta?.pdfSupplementalTitle ?? '')
const pdfSupplementalDescription = computed(() => props.cal?.pdfSupplementalDescription ?? props.cal?.meta?.pdfSupplementalDescription ?? '')
const pdfSupplementalLinks = computed(() =>
  (((props.cal?.pdfSupplementalLinks ?? props.cal?.meta?.pdfSupplementalLinks ?? []) as Array<{ label?: string; url?: string }>)
    .filter(link => link.label && link.url))
)

const copied = ref(false)
const icsHref = computed(() => `/calendars/${props.district.slug}-${props.cal.schoolYear}.ics`)
const icsFilename = computed(() => `${props.district.slug}-${props.cal.schoolYear}.ics`)
const calendarShortName = computed(() => props.district?.shortName || props.districtName)
const icsHeading = computed(() =>
  props.cal?.icsHeading ?? props.cal?.meta?.icsHeading ?? `Download the ${displayYear.value} Calendar`
)
const icsDescription = computed(() =>
  props.cal?.icsDescription ?? props.cal?.meta?.icsDescription ?? `Download these dates as an ICS file for Google Calendar, Apple Calendar, or Outlook. This is a one-time import and will not update automatically if the district changes its calendar.`
)
const icsButtonLabel = computed(() => {
  return props.cal?.icsButtonLabel ?? props.cal?.meta?.icsButtonLabel ?? `Download ICS Calendar`
})
const icsButtonSupportText = computed(() =>
  props.cal?.icsButtonSupportText ?? props.cal?.meta?.icsButtonSupportText ?? 'One-time import. This calendar does not automatically sync with later district updates.'
)
const compatibleCalendars = ['Apple Calendar', 'Google Calendar', 'Outlook']
const icsIncludedItems = computed(() => {
  const events = (props.cal?.events ?? []).filter((event: any) => !event.hideFromCalendarExport)
  const hasType = (types: string[]) => events.some((event: any) => types.includes(event.type))
  const items = ['student holidays', 'break ranges']
  if (hasType(['no_school', 'student_holiday'])) items.push('student no-school dates')
  if (hasType(['early_dismissal', 'early_release'])) items.push('early-release dates')
  if (hasType(['school_resume', 'school_reopen'])) items.push('school resume dates')
  if (hasType(['academic', 'quarter_end', 'semester_end'])) items.push('key academic dates')
  return [...new Set(items)]
})
const icsIncludedText = computed(() => {
  const items = icsIncludedItems.value
  if (items.length <= 1) return items[0] ?? 'school calendar dates'
  return `${items.slice(0, -1).join(', ')}, and ${items[items.length - 1]}`
})
function copyLink() {
  navigator.clipboard.writeText(window.location.href)
  copied.value = true
  setTimeout(() => { copied.value = false }, 2000)
}
function shareWhatsApp() {
  const text = encodeURIComponent(`${props.districtName} ${props.year} school calendar — ${window.location.href}`)
  window.open(`https://wa.me/?text=${text}`, '_blank')
}
function shareSMS() {
  const text = encodeURIComponent(`${props.districtName} ${props.year} school calendar: ${window.location.href}`)
  window.open(`sms:?body=${text}`)
}
function shareX() {
  const params = new URLSearchParams({
    text: `${props.districtName} ${props.year} school calendar`,
    url: window.location.href,
  })
  window.open(`https://x.com/intent/post?${params.toString()}`, '_blank', 'noopener,noreferrer')
}
function shareFacebook() {
  const params = new URLSearchParams({ u: window.location.href })
  window.open(`https://www.facebook.com/sharer/sharer.php?${params.toString()}`, '_blank', 'noopener,noreferrer')
}
function printCalendar() {
  const calendar = document.getElementById('all-dates')
  if (!calendar) return

  const printSheet = document.createElement('div')
  const calendarClone = calendar.cloneNode(true) as HTMLElement
  printSheet.className = 'calendar-print-sheet'
  calendarClone.removeAttribute('id')
  calendarClone.querySelectorAll('[id]').forEach(element => element.removeAttribute('id'))
  printSheet.appendChild(calendarClone)
  document.body.appendChild(printSheet)
  document.body.classList.add('calendar-print-mode')

  const cleanup = () => {
    document.body.classList.remove('calendar-print-mode')
    printSheet.remove()
  }

  window.addEventListener('afterprint', cleanup, { once: true })
  window.requestAnimationFrame(() => window.print())
}
const icsAriaLabel = computed(() =>
  props.cal?.icsAriaLabel ?? props.cal?.meta?.icsAriaLabel ?? `Download ${props.districtName} ${props.year} calendar file for Google Calendar, Apple Calendar, and Outlook`
)
</script>

<template>
  <div id="add-to-calendar" class="bg-rds-surface-panel rounded-lg border border-rds-hairline overflow-hidden scroll-mt-24 shadow-[0_1px_0_rgba(31,41,51,0.03)]">
    <div v-if="unifiedDownloadTitle" class="p-6 border-b border-[#ebe6dd]">
      <h2 class="text-lg font-semibold text-[#1f2933] mb-1">{{ unifiedDownloadTitle }}</h2>
      <p v-if="unifiedDownloadDescription" class="text-sm text-[#6b645c]">{{ unifiedDownloadDescription }}</p>
    </div>

    <div v-if="officialSubscriptionUrl" class="p-6 border-b border-[#ebe6dd]">
      <h3 class="text-base font-semibold text-[#1f2933] mb-1">{{ officialSubscriptionTitle }}</h3>
      <p class="text-sm text-[#6b645c] mb-4">{{ officialSubscriptionDescription }}</p>
      <a
        :href="officialSubscriptionUrl"
        target="_blank"
        rel="noopener"
        class="inline-flex items-center gap-2 px-4 py-2.5 bg-[#315b39] hover:bg-[#284b30] active:scale-[0.99] transition-all text-white text-sm font-semibold rounded-lg shadow-sm"
      >
        {{ officialSubscriptionButtonLabel }}
        <span class="sr-only">(opens in a new tab)</span>
      </a>
    </div>

    <!-- Add to Calendar -->
    <div class="p-6 border-b border-[#ebe6dd]">
      <component :is="unifiedDownloadTitle ? 'h3' : 'h2'" class="text-lg font-semibold text-[#1f2933] mb-1">{{ icsHeading }}</component>
      <p class="text-sm text-[#6b645c] mb-4">
        {{ icsDescription }}
      </p>
      <!-- Primary CTA -->
      <a
        :href="icsHref"
        :download="icsFilename"
        :aria-label="icsAriaLabel"
        class="w-full flex items-center justify-center gap-2.5 px-4 py-3 mb-3 rounded-lg bg-[#0f5d6b] hover:bg-[#0b4c58] active:scale-[0.99] transition-all text-white font-semibold text-sm shadow-sm"
      >
        <svg class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true" focusable="false">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
        </svg>
        {{ icsButtonLabel }}
      </a>
      <p v-if="!hideIcsButtonSupportText" class="mb-3 text-center text-xs font-medium text-[#6b645c]">
        {{ icsButtonSupportText }}
      </p>
      <div v-if="!hideCompatibleCalendars" class="rounded-lg border border-[#e1dbd0] bg-[#f3f0e8] px-4 py-3">
        <p class="text-xs font-medium text-[#7b756d] mb-2">Compatible with</p>
        <ul class="flex flex-wrap gap-2" aria-label="Compatible calendar apps">
          <li
            v-for="calendarName in compatibleCalendars"
            :key="calendarName"
            class="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-[#fbfaf7] border border-[#e1dbd0] text-xs font-medium text-[#4f5b5f]"
          >
            <svg class="w-3.5 h-3.5 text-[#8f8a82]" viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true" focusable="false">
              <rect x="3" y="4" width="18" height="18" rx="2" stroke-width="1.5"/>
              <path d="M3 9h18" stroke-width="1.5"/>
              <path d="M8 2v4M16 2v4" stroke-width="1.5" stroke-linecap="round"/>
            </svg>
            {{ calendarName }}
          </li>
        </ul>
      </div>
      <p v-if="!compactDownloadModule" class="text-xs text-[#6b645c] mt-3">
        The .ics file is generated from the reviewed calendar records used for this page. After downloading, import the file into your preferred calendar app.
      </p>
      <p v-if="!compactDownloadModule" class="text-xs text-[#6b645c] mt-2">
        This calendar import file is generated from verified {{ year }} {{ districtName }} district calendar data. It is an independent one-time import from MySchoolDates and will not automatically update if the district revises its calendar, so always verify schedule changes with the district.
      </p>
    </div>

    <!-- PDF Download -->
    <div v-if="pdfUrl" class="p-6 border-b border-[#ebe6dd]">
      <component :is="compactDownloadModule ? 'h3' : 'h2'" class="text-base font-semibold text-[#1f2933] mb-1">{{ pdfHeading }}</component>
      <p v-if="pdfVersionLabel && !hidePdfVersionLabel" class="text-xs font-medium text-[#6b645c] mb-2">{{ pdfVersionLabel }}</p>
      <p class="text-sm text-[#6b645c] mb-4">{{ pdfDescription }}</p>
      <div class="flex flex-wrap gap-3">
        <a
          :href="pdfUrl"
          target="_blank"
          rel="noopener"
          class="inline-flex items-center gap-2 px-4 py-2.5 bg-[#8a4b3a] hover:bg-[#743c2f] active:scale-[0.99] transition-all text-white text-sm font-semibold rounded-lg shadow-sm"
        >
          <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true" focusable="false">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
          </svg>
          {{ pdfButtonLabel }}
          <span class="sr-only">(opens in a new tab)</span>
        </a>
        <a
          v-if="!hideCalendarUpdatesButton"
          :href="sourceUrl"
          target="_blank"
          rel="noopener"
          class="inline-flex items-center gap-2 px-4 py-2.5 border border-[#d9d2c7] hover:border-[#b8c9c9] hover:bg-[#f3f0e8] active:scale-[0.99] transition-all text-[#4f5b5f] text-sm font-semibold rounded-lg"
        >
          Check for Calendar Updates
          <span class="sr-only">(opens in a new tab)</span>
        </a>
      </div>
      <div v-if="pdfSupplementalTitle || pdfSupplementalDescription || pdfSupplementalLinks.length" class="mt-4 rounded-lg border border-[#e1dbd0] bg-[#f8f5ee] px-4 py-3">
        <p v-if="pdfSupplementalTitle" class="text-xs font-semibold uppercase tracking-wide text-[#6b645c]">{{ pdfSupplementalTitle }}</p>
        <p v-if="pdfSupplementalDescription" class="mt-1 text-xs leading-relaxed text-[#6b645c]">{{ pdfSupplementalDescription }}</p>
        <p v-if="pdfSupplementalLinks.length" class="mt-2 text-xs">
          <a
            v-for="(link, index) in pdfSupplementalLinks"
            :key="link.url"
            :href="link.url"
            target="_blank"
            rel="noopener"
            class="font-medium text-[#0f5d6b] underline hover:text-[#0b4c58]"
          >
            {{ index ? ' · ' : '' }}{{ link.label }}<span class="sr-only">(opens in a new tab)</span>
          </a>
        </p>
      </div>
    </div>

    <!-- Share with Parents -->
    <div class="p-6">
      <component v-if="!hideShareCalendarHeading" :is="compactDownloadModule ? 'h3' : 'h2'" class="text-base font-semibold text-[#1f2933] mb-3">Share This Calendar</component>
      <div class="flex flex-wrap gap-3">
        <!-- Copy Link -->
        <button
          type="button"
          @click="copyLink"
          class="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-[#d9d2c7] hover:border-[#b8c9c9] text-sm font-medium text-[#4f5b5f] hover:bg-[#f3f0e8] active:scale-[0.99] transition-all"
        >
          <svg v-if="!copied" class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true" focusable="false">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
          </svg>
          <svg v-else class="w-4 h-4 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true" focusable="false">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
          </svg>
          {{ copied ? 'Copied!' : 'Copy Link' }}
        </button>
        <span class="sr-only" aria-live="polite">{{ copied ? 'Link copied to clipboard.' : '' }}</span>
        <!-- Print -->
        <button
          type="button"
          @click="printCalendar"
          class="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-[#d9d2c7] hover:border-[#b8c9c9] hover:bg-[#e6f0ef] text-sm font-medium text-[#4f5b5f] transition-all"
        >
          <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true" focusable="false">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 9V4h12v5M6 18H5a2 2 0 01-2-2v-5a2 2 0 012-2h14a2 2 0 012 2v5a2 2 0 01-2 2h-1M6 14h12v6H6v-6z" />
          </svg>
          Print Calendar
        </button>
        <!-- WhatsApp -->
        <button
          type="button"
          @click="shareWhatsApp"
          class="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-[#d9d2c7] hover:border-[#aec2b1] hover:bg-[#e7efe5] text-sm font-medium text-[#4f5b5f] transition-all"
        >
          <svg class="w-4 h-4 text-green-500" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" focusable="false">
            <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347z"/>
            <path d="M12 0C5.373 0 0 5.373 0 12s5.373 12 12 12 12-5.373 12-12S18.627 0 12 0zm.029 18.88a7.947 7.947 0 01-3.794-.964l-4.21 1.104 1.126-4.108a7.934 7.934 0 01-1.062-3.965C4.09 7.148 7.666 3.573 12.03 3.573c2.116 0 4.099.823 5.59 2.317a7.862 7.862 0 012.31 5.587c-.002 4.358-3.579 7.403-7.901 7.403z"/>
          </svg>
          WhatsApp
        </button>
        <!-- Text / SMS -->
        <button
          type="button"
          @click="shareSMS"
          class="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-[#d9d2c7] hover:border-[#b8c9c9] hover:bg-[#f3f0e8] text-sm font-medium text-[#4f5b5f] transition-all"
        >
          <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true" focusable="false">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z" />
          </svg>
          Text
        </button>
        <!-- Facebook -->
        <button
          type="button"
          @click="shareFacebook"
          class="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-[#d9d2c7] hover:border-[#9eb7dc] hover:bg-[#eaf1fb] text-sm font-medium text-[#4f5b5f] transition-all"
        >
          <svg class="w-4 h-4 text-[#1877f2]" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" focusable="false">
            <path d="M24 12.073C24 5.405 18.627.032 12 .032S0 5.405 0 12.073c0 6.027 4.388 11.024 10.125 11.93v-8.436H7.078v-3.494h3.047V9.41c0-3.027 1.792-4.7 4.533-4.7 1.312 0 2.686.236 2.686.236v2.972H15.83c-1.491 0-1.956.931-1.956 1.886v2.269h3.328l-.532 3.494h-2.796v8.436C19.612 23.097 24 18.1 24 12.073Z" />
          </svg>
          Facebook
        </button>
        <!-- X -->
        <button
          type="button"
          @click="shareX"
          class="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-[#d9d2c7] hover:border-[#9fa3a7] hover:bg-[#eef0f1] text-sm font-medium text-[#4f5b5f] transition-all"
        >
          <svg class="w-4 h-4 text-[#1f2933]" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" focusable="false">
            <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231 5.451-6.231Zm-1.161 17.52h1.833L7.084 4.126H5.117L17.083 19.77Z" />
          </svg>
          X
        </button>
      </div>
    </div>
  </div>
</template>
