<script setup lang="ts">
const props = defineProps<{
  districtName: string
  year: string
  sourceUrl: string
  district: any
  cal: any
}>()

const pdfUrl = computed(() => String(props.cal?.sourcePdfUrl ?? props.cal?.printablePdfUrl ?? ''))
const hasOfficialPdf = computed(() => Boolean(props.cal?.sourcePdfUrl))
const hasGeneratedPrintablePdf = computed(() => !hasOfficialPdf.value && Boolean(props.cal?.printablePdfUrl))
const isDrivePdf = computed(() => pdfUrl.value.includes('drive.google.com'))
const isArchivedPdfCopy = computed(() => pdfUrl.value.includes('assets.myschooldates.com'))
const pdfHeading = computed(() => isArchivedPdfCopy.value
  ? `${props.districtName} Calendar ${props.year}: Official Calendar PDF — Archived Copy`
  : hasGeneratedPrintablePdf.value
  ? `${props.districtName} Calendar ${props.year}: Printable PDF`
  : isDrivePdf.value
  ? `${props.districtName} Calendar ${props.year}: Printable PDF`
  : `${props.districtName} Calendar ${props.year}: Printable PDF`
)
const pdfDescription = computed(() => isArchivedPdfCopy.value
  ? `This is an archived copy of the official ${props.year} calendar published by ${props.districtName}. MySchoolDates stores the file for reliable long-term access because original district file URLs may expire. Check the official district source for revisions or newer versions.`
  : hasGeneratedPrintablePdf.value
  ? `Download a printable PDF generated by MySchoolDates from the reviewed ${props.year} ${props.districtName} calendar records. The official district calendar remains the source of record for revisions and last-minute changes.`
  : isDrivePdf.value
  ? `Open or print the calendar PDF linked from the ${props.districtName} calendar page. Verify the latest version on the official district source before making critical plans.`
  : `Open or print the official calendar PDF published by ${props.districtName}. Verify the latest version on the official district source before making critical plans.`
)
const pdfButtonLabel = computed(() => {
  if (isArchivedPdfCopy.value) return 'View Archived Copy of Official PDF'
  if (hasGeneratedPrintablePdf.value) return 'Download Printable PDF Calendar'
  if (isDrivePdf.value) return 'Download PDF'
  return 'View Official PDF'
})

const copied = ref(false)
const icsHref = computed(() => `/calendars/${props.district.slug}-${props.cal.schoolYear}.ics`)
const icsFilename = computed(() => `${props.district.slug}-${props.cal.schoolYear}.ics`)
const calendarShortName = computed(() => props.district?.shortName || props.districtName)
const icsHeading = computed(() => `${calendarShortName.value} Calendar ${props.year} ICS File`)
const icsButtonLabel = computed(() => {
  return `Download calendar file for Google Calendar, Apple Calendar, and Outlook`
})
const compatibleCalendars = ['Apple Calendar', 'Google Calendar', 'Outlook']
const icsIncludedItems = computed(() => {
  const events = props.cal?.events ?? []
  const hasType = (types: string[]) => events.some((event: any) => types.includes(event.type))
  const items = ['student holidays', 'break ranges']
  if (hasType(['no_school', 'student_holiday'])) items.push('student no-school dates')
  if (hasType(['early_dismissal', 'early_release'])) items.push('early-release dates')
  if (hasType(['school_resume', 'school_reopen'])) items.push('school resume dates')
  if (hasType(['academic', 'quarter_end', 'semester_end'])) items.push('key academic dates')
  return [...new Set(items)]
})
const icsIncludedText = computed(() => {
  const items = icsIncludedItems.value
  if (items.length <= 1) return items[0] ?? 'school calendar dates'
  return `${items.slice(0, -1).join(', ')}, and ${items[items.length - 1]}`
})
function copyLink() {
  navigator.clipboard.writeText(window.location.href)
  copied.value = true
  setTimeout(() => { copied.value = false }, 2000)
}
function shareWhatsApp() {
  const text = encodeURIComponent(`${props.districtName} ${props.year} school calendar — ${window.location.href}`)
  window.open(`https://wa.me/?text=${text}`, '_blank')
}
function shareSMS() {
  const text = encodeURIComponent(`${props.districtName} ${props.year} school calendar: ${window.location.href}`)
  window.open(`sms:?body=${text}`)
}
function printCalendar() {
  window.print()
}
const icsAriaLabel = computed(() => `Download ${props.districtName} ${props.year} calendar file for Google Calendar, Apple Calendar, and Outlook`)
</script>

<template>
  <div id="add-to-calendar" class="bg-white rounded-xl border border-gray-200 overflow-hidden scroll-mt-24">
    <!-- Add to Calendar -->
    <div class="p-6 border-b border-gray-100">
      <h2 class="text-lg font-semibold text-gray-900 mb-1">{{ icsHeading }}</h2>
      <p class="text-sm text-gray-500 mb-4">
        Never miss a school holiday or early dismissal. Download one standard .ics file containing {{ icsIncludedText }}.
      </p>
      <!-- Primary CTA -->
      <a
        :href="icsHref"
        :download="icsFilename"
        :aria-label="icsAriaLabel"
        class="w-full flex items-center justify-center gap-2.5 px-4 py-3 mb-3 rounded-xl bg-blue-600 hover:bg-blue-700 active:scale-95 transition-all text-white font-semibold text-sm shadow-sm"
      >
        <svg class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
        </svg>
        {{ icsButtonLabel }}
      </a>
      <p class="mb-3 text-center text-xs font-medium text-gray-500">
        One-time calendar download. Not a live district sync.
      </p>
      <div class="rounded-xl border border-gray-200 bg-gray-50 px-4 py-3">
        <p class="text-xs font-medium text-gray-500 mb-2">Compatible with</p>
        <ul class="flex flex-wrap gap-2" aria-label="Compatible calendar apps">
          <li
            v-for="calendarName in compatibleCalendars"
            :key="calendarName"
            class="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-white border border-gray-200 text-xs font-medium text-gray-700"
          >
            <svg class="w-3.5 h-3.5 text-gray-400" viewBox="0 0 24 24" fill="none" stroke="currentColor">
              <rect x="3" y="4" width="18" height="18" rx="2" stroke-width="1.5"/>
              <path d="M3 9h18" stroke-width="1.5"/>
              <path d="M8 2v4M16 2v4" stroke-width="1.5" stroke-linecap="round"/>
            </svg>
            {{ calendarName }}
          </li>
        </ul>
      </div>
      <p class="text-xs text-gray-600 mt-3">
        The .ics file is generated from the reviewed calendar records used for this page. After downloading, import the file into your preferred calendar app.
      </p>
      <p class="text-xs text-gray-600 mt-2">
        This calendar import file is generated from verified {{ year }} {{ districtName }} district calendar data. It is an independent one-time import from MySchoolDates and will not automatically update if the district revises its calendar, so always verify schedule changes with the district.
      </p>
    </div>

    <!-- PDF Download -->
    <div v-if="pdfUrl" class="p-6 border-b border-gray-100">
      <h2 class="text-lg font-semibold text-gray-900 mb-1">{{ pdfHeading }}</h2>
      <p class="text-sm text-gray-500 mb-4">{{ pdfDescription }}</p>
      <div class="flex flex-wrap gap-3">
        <a
          :href="pdfUrl"
          target="_blank"
          rel="noopener"
          class="inline-flex items-center gap-2 px-4 py-2.5 bg-red-600 hover:bg-red-700 active:scale-95 transition-all text-white text-sm font-semibold rounded-lg shadow-sm"
        >
          <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
          </svg>
          {{ pdfButtonLabel }}
          <span class="sr-only">(opens in a new tab)</span>
        </a>
        <a
          :href="sourceUrl"
          target="_blank"
          rel="noopener"
          class="inline-flex items-center gap-2 px-4 py-2.5 border border-gray-200 hover:border-gray-300 hover:bg-gray-50 active:scale-95 transition-all text-gray-700 text-sm font-semibold rounded-lg"
        >
          Verify on official source
          <span class="sr-only">(opens in a new tab)</span>
        </a>
      </div>
    </div>

    <!-- Share with Parents -->
    <div class="p-6">
      <h2 class="text-base font-semibold text-gray-900 mb-3">Share with Parents</h2>
      <div class="flex flex-wrap gap-3">
        <!-- Copy Link -->
        <button
          type="button"
          @click="copyLink"
          class="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-gray-200 hover:border-gray-300 text-sm font-medium text-gray-700 hover:bg-gray-50 active:scale-95 transition-all"
        >
          <svg v-if="!copied" class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
          </svg>
          <svg v-else class="w-4 h-4 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
          </svg>
          {{ copied ? 'Copied!' : 'Copy Link' }}
        </button>
        <span class="sr-only" aria-live="polite">{{ copied ? 'Link copied to clipboard.' : '' }}</span>
        <!-- Print -->
        <button
          type="button"
          @click="printCalendar"
          class="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-gray-200 hover:border-blue-300 hover:bg-blue-50 text-sm font-medium text-gray-700 transition-all"
        >
          <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 9V4h12v5M6 18H5a2 2 0 01-2-2v-5a2 2 0 012-2h14a2 2 0 012 2v5a2 2 0 01-2 2h-1M6 14h12v6H6v-6z" />
          </svg>
          Print Calendar
        </button>
        <!-- WhatsApp -->
        <button
          type="button"
          @click="shareWhatsApp"
          class="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-gray-200 hover:border-green-300 hover:bg-green-50 text-sm font-medium text-gray-700 transition-all"
        >
          <svg class="w-4 h-4 text-green-500" viewBox="0 0 24 24" fill="currentColor">
            <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347z"/>
            <path d="M12 0C5.373 0 0 5.373 0 12s5.373 12 12 12 12-5.373 12-12S18.627 0 12 0zm.029 18.88a7.947 7.947 0 01-3.794-.964l-4.21 1.104 1.126-4.108a7.934 7.934 0 01-1.062-3.965C4.09 7.148 7.666 3.573 12.03 3.573c2.116 0 4.099.823 5.59 2.317a7.862 7.862 0 012.31 5.587c-.002 4.358-3.579 7.403-7.901 7.403z"/>
          </svg>
          WhatsApp
        </button>
        <!-- Text / SMS -->
        <button
          type="button"
          @click="shareSMS"
          class="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-gray-200 hover:border-gray-300 hover:bg-gray-50 text-sm font-medium text-gray-700 transition-all"
        >
          <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z" />
          </svg>
          Text
        </button>
      </div>
    </div>
  </div>
</template>
