import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

type DistrictRecord = {
  institutionId: string
  name: string
  shortName?: string
  slug: string
}

type CalendarEvent = {
  date: string
  name: string
  type: string
  description?: string
}

type CalendarRecord = {
  schoolYear: string
  firstDay?: string
  lastDay?: string
  totalSchoolDays?: number
  events: CalendarEvent[]
}

function parseDate(date: string) {
  return new Date(`${date}T00:00:00`)
}

function dateKey(date: Date) {
  const y = date.getFullYear()
  const m = String(date.getMonth() + 1).padStart(2, '0')
  const d = String(date.getDate()).padStart(2, '0')
  return `${y}-${m}-${d}`
}

function compactDate(date: string) {
  return date.replace(/-/g, '')
}

function escapeText(value: string) {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/\n/g, '\\n')
    .replace(/,/g, '\\,')
    .replace(/;/g, '\\;')
}

function escapePdfText(value: string) {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
}

function wrapText(value: string, maxLength = 82) {
  const words = value.split(/\s+/)
  const lines: string[] = []
  let current = ''

  for (const word of words) {
    const next = current ? `${current} ${word}` : word
    if (next.length > maxLength && current) {
      lines.push(current)
      current = word
    } else {
      current = next
    }
  }

  if (current) lines.push(current)
  return lines
}

function getBreaks(events: CalendarEvent[]) {
  return events
    .filter(event => event.type === 'break_start')
    .map((start) => {
      const end = events.find(event =>
        event.type === 'break_end' &&
        event.date >= start.date &&
        event.name.replace(/\s+End$/i, '').toLowerCase() === start.name.toLowerCase()
      )
      return {
        name: start.name,
        start: start.date,
        end: end?.date ?? start.date,
      }
    })
}

function isCoveredByBreak(event: CalendarEvent, events: CalendarEvent[]) {
  if (event.type === 'break_start' || event.type === 'break_end' || event.type === 'school_resume') return false
  return getBreaks(events).some(breakRange =>
    event.date >= breakRange.start &&
    event.date <= breakRange.end
  )
}

function findCalendarFile(root: string, fileParam: string) {
  const normalizedFileParam = fileParam.replace(/\.(ics|pdf)$/i, '')
  const match = normalizedFileParam.match(/^(.+)-(\d{4}-\d{4})$/)
  if (!match) return null

  const [, slug, schoolYear] = match
  const districtDir = join(root, 'content', 'districts')

  for (const file of readdirSync(districtDir)) {
    if (!file.endsWith('.json')) continue
    const district = JSON.parse(readFileSync(join(districtDir, file), 'utf-8')) as DistrictRecord
    if (district.slug !== slug) continue

    const calendarPath = join(root, 'content', 'calendars', district.institutionId, `${schoolYear}.json`)
    if (!existsSync(calendarPath)) return null

    return {
      district,
      calendarPath,
      schoolYear,
    }
  }

  return null
}

function buildIcs(district: DistrictRecord, calendar: CalendarRecord) {
  const lines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//MySchoolDates//School Calendar//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:${escapeText(`${district.name} ${calendar.schoolYear}`)}`,
  ]

  const breaks = getBreaks(calendar.events)
  const eventsForExport = calendar.events.filter(event =>
    event.type !== 'break_end' &&
    !isCoveredByBreak(event, calendar.events)
  )

  for (const event of eventsForExport) {
    const breakRange = event.type === 'break_start'
      ? breaks.find(item => item.name === event.name && item.start === event.date)
      : null
    const eventEndDate = breakRange?.end ?? event.date
    const nextDay = parseDate(eventEndDate)
    nextDay.setDate(nextDay.getDate() + 1)

    const start = compactDate(event.date)
    const end = compactDate(dateKey(nextDay))
    const uidSlug = district.slug.replace(/[^a-z0-9-]/gi, '-').toLowerCase()

    lines.push(
      'BEGIN:VEVENT',
      `DTSTAMP:${start}T000000Z`,
      `DTSTART;VALUE=DATE:${start}`,
      `DTEND;VALUE=DATE:${end}`,
      `SUMMARY:${escapeText(`${event.name} - ${district.name}`)}`,
      ...(event.description ? [`DESCRIPTION:${escapeText(event.description)}`] : []),
      `UID:${start}-${end}-${event.type}-${uidSlug}@myschooldates.com`,
      'END:VEVENT',
    )
  }

  lines.push('END:VCALENDAR')
  return `${lines.join('\r\n')}\r\n`
}

function buildPdf(district: DistrictRecord, calendar: CalendarRecord) {
  const title = `${district.shortName ?? district.name} Calendar ${calendar.schoolYear}`
  const subtitle = 'Printable school calendar generated by MySchoolDates from reviewed district calendar records.'
  const keyDates = [
    calendar.firstDay ? `First day of school: ${calendar.firstDay}` : null,
    calendar.lastDay ? `Last day of school: ${calendar.lastDay}` : null,
    calendar.totalSchoolDays ? `Instructional days: ${calendar.totalSchoolDays}` : null,
  ].filter(Boolean) as string[]
  const eventLines = calendar.events.map(event => `${event.date}  ${event.name}${event.description ? ` - ${event.description}` : ''}`)
  const lines = [
    title,
    subtitle,
    '',
    ...keyDates,
    '',
    'Important Dates',
    ...eventLines,
    '',
    'Source note: This printable PDF is generated by MySchoolDates for family planning. The official district calendar remains the source of record for revisions and last-minute changes.',
  ].flatMap(line => line ? wrapText(line) : [''])

  const pages: string[] = []
  let commands = [
    'BT',
    '/F1 18 Tf',
    '72 740 Td',
    `(${escapePdfText(lines[0] ?? title)}) Tj`,
    '/F1 10 Tf',
  ]
  let y = 716

  for (const line of lines.slice(1)) {
    if (y < 72) {
      commands.push('ET')
      pages.push(commands.join('\n'))
      commands = ['BT', '/F1 10 Tf', '72 740 Td']
      y = 740
    } else {
      commands.push('0 -16 Td')
      y -= 16
    }
    commands.push(`(${escapePdfText(line)}) Tj`)
  }

  commands.push('ET')
  pages.push(commands.join('\n'))

  const objects: string[] = []
  const addObject = (body: string) => {
    objects.push(body)
    return objects.length
  }

  const catalogId = addObject('<< /Type /Catalog /Pages 2 0 R >>')
  const pagesId = addObject('')
  const fontId = addObject('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>')
  const pageIds: number[] = []

  for (const pageContent of pages) {
    const contentId = addObject(`<< /Length ${Buffer.byteLength(pageContent, 'utf8')} >>\nstream\n${pageContent}\nendstream`)
    const pageId = addObject(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${contentId} 0 R >>`)
    pageIds.push(pageId)
  }

  objects[pagesId - 1] = `<< /Type /Pages /Kids [${pageIds.map(id => `${id} 0 R`).join(' ')}] /Count ${pageIds.length} >>`
  objects[catalogId - 1] = '<< /Type /Catalog /Pages 2 0 R >>'

  let pdf = '%PDF-1.4\n'
  const offsets = [0]
  for (let i = 0; i < objects.length; i++) {
    offsets.push(Buffer.byteLength(pdf, 'utf8'))
    pdf += `${i + 1} 0 obj\n${objects[i]}\nendobj\n`
  }
  const xrefOffset = Buffer.byteLength(pdf, 'utf8')
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`
  for (const offset of offsets.slice(1)) {
    pdf += `${String(offset).padStart(10, '0')} 00000 n \n`
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`

  return Buffer.from(pdf, 'utf8')
}

export default defineEventHandler((event) => {
  const fileParam = getRouterParam(event, 'file') ?? ''
  const root = process.cwd()
  const match = findCalendarFile(root, fileParam)

  if (!match) {
    throw createError({ statusCode: 404, statusMessage: 'Calendar file not found' })
  }

  const calendar = JSON.parse(readFileSync(match.calendarPath, 'utf-8')) as CalendarRecord
  const isPdfRequest = fileParam.toLowerCase().endsWith('.pdf')
  const filename = `${match.district.slug}-${match.schoolYear}.${isPdfRequest ? 'pdf' : 'ics'}`

  if (isPdfRequest) {
    const body = buildPdf(match.district, calendar)
    setHeader(event, 'Content-Type', 'application/pdf')
    setHeader(event, 'Content-Disposition', `inline; filename="${filename}"`)
    setHeader(event, 'X-Robots-Tag', 'noindex')
    setHeader(event, 'Cache-Control', 'public, max-age=3600')
    return body
  }

  const body = buildIcs(match.district, calendar)
  setHeader(event, 'Content-Type', 'text/calendar; charset=utf-8')
  setHeader(event, 'Content-Disposition', `attachment; filename="${filename}"`)
  setHeader(event, 'X-Robots-Tag', 'noindex')
  setHeader(event, 'Cache-Control', 'public, max-age=3600')
  return body
})
